#!/usr/bin/env python
# -*- coding: utf-8 -*-


import argparse
import numpy as np
import matplotlib.pyplot as plt
from schimpy.schism_mesh import read_mesh, write_mesh
from schimpy.split_quad import calculate_internal_angles


def create_arg_parser():
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=str)
    parser.add_argument('--output', type=str)
    parser.add_argument('--skewness', type=float, default=0.02)
    parser.add_argument('--plot', type=bool, default=True)
    return parser

def remove_skewed_cells(infile, outfile, skew_thr=0.02, ifplot=True):
    """ removed cells that are to skewed
    
    This function takes the mesh generated by prep_mesh_dist.py and remove the
    cells that have skewenss larger than the provided threshold.
    
    Parameters
    ----------
    
    infile : str
    Name of the hgrid.gr3
    
    outfile : str
    Name of the output file.
    
    skew_thr : float
    Threshold for skewest factor, default = 0.02 

 
    ifplot : bool
    if a plot of the final grid is generated
    
    """ 
    
    mesh = read_mesh(infile)
    skewness = calculate_skewness(mesh)
    degenerate = np.argwhere(skewness < skew_thr)
    print("Elements to remove: {}".format(degenerate))
    for i in degenerate:
        mesh.mark_elem_deleted(i)
    mesh.renumber()
    write_mesh(mesh, outfile)
    if ifplot:
        fig = plt.figure()
        ax = fig.add_subplot(111)
        ax.hist(skewness, bins=20, log=True)
        ax.set_xlabel('Skewness')
        ax.set_ylabel('Count of cells')
        plt.show()
    

def calculate_skewness(mesh):
    """ Assuming all triangular
    """
    angles = []
    for elem in mesh.elems:
        nodes = mesh.nodes[elem]
        angles.append(calculate_internal_angles(nodes))
    angles = np.array(angles)
    theta_max = np.max(angles, axis=1)
    theta_min = np.min(angles, axis=1)
    theta_e = np.pi / 3.
    skewness = 1. - np.maximum((theta_max - theta_e) / (np.pi - theta_e), 1. -  theta_min / theta_e)
    return skewness


def main():
    parser = create_arg_parser()
    args = parser.parse_args()
    
    # So that it works also using using conda inline command.
    infile = args.input
    outfile = args.output
    skew_thr = args.skewness
    ifplot = args.plot
    
    remove_skewed_cells(infile, outfile, skew_thr, ifplot)
    
   
if __name__ == '__main__':
    main()
